services:
  poker-planner-app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 8080:5173
    volumes:
      - ./app:/app
#      - ./app/node_modules:/project/node_modules
#
  poker-planner-api:
    build:
       context: ./api
    ports:
      - 8081:8000
    volumes:
      - ./api:/app
